// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const config =  {
    API: {
        GraphQL: {
          endpoint: 'https://2bvzbtubrbcbpo4dfef4ygiwaq.appsync-api.ca-central-1.amazonaws.com/graphql',
          region: 'ca-central-1',
          defaultAuthMode: 'apiKey',
          apiKey: 'da2-hgeghxwxirgovjwk5fps2hhwda'
        }
    }
};

export default config;